services:
  agents:
    build:
      context: ./agents
      dockerfile: Dockerfile
    container_name: agents_service
    env_file:
      - .env
    ports:
      - "8501:8501"
    networks:
        - network-agentes
    environment:
      PYTHONUNBUFFERED: 1
      
  discord-bot:
    build:
      context: ./discord
      dockerfile: Dockerfile
    container_name: discord_bot_service
    env_file:
      - .env
    networks:
      - network-agentes
    environment:
      PYTHONUNBUFFERED: 1
networks:
  network-agentes:
    external: true